# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23e1219a10c6e654b8f3c12b0722a84b14064026d6b6c4a2b7c98d677fb5d9009e005b0f521f0a7dfb99aa200b4831425ed52cf913f8e482b8a4e5ac0c0fa53a

test:
  secret_key_base: 17a1b49d7e84b8d52b288cc8399620a83e971280b52558e8b7bab8603b66e24c7c980c94afcc161d4e9be78d26f391e2d61e8ae0bb35be91e10f7af904128752

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
